src/marketplace/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView, TemplateView

from .views import common, org, proj, user, admin


# Set URL namespace
app_name = 'marketplace'

urlpatterns = [
    path('', user.home_view, name='home'),

    path('about/', common.about_view, name='about'),
    path('resources/', common.resources_view, name='resources'),

    path('terms/', RedirectView.as_view(pattern_name='marketplace:terms-20200804'), name='terms'),
    path('terms-20200804.html',
         TemplateView.as_view(template_name='marketplace/terms/terms-20200804.html',
                              extra_context={'privacy_url': 'marketplace:privacy-20200804'}),
         name='terms-20200804'),

    path('privacy/', RedirectView.as_view(pattern_name='marketplace:privacy-20200804'), name='privacy'),
    path('privacy-20200804.html',
         TemplateView.as_view(template_name='marketplace/privacy/privacy-20200804.html',
                              extra_context={'terms_url': 'marketplace:terms-20200804'}),
         name='privacy-20200804'),

    path('org/', org.organization_list_view, name='org_list'),
    path('org/create', org.OrganizationCreateView.as_view(), name='org_create'),
    path('org/create/<str:type>', org.OrganizationCreateView.as_view(), name='org_create_type'),
    path('org/<int:org_pk>/', org.OrganizationView.as_view(), name='org_info'),
    path('org/<int:org_pk>/edit', org.OrganizationEdit.as_view(), name='org_info_edit'),
    path('org/<int:org_pk>/staff/', org.organization_staff_view, name='org_staff'),
    path('org/<int:org_pk>/staff/add', org.add_organization_staff_view, name='org_staff_add'),
    path('org/<int:org_pk>/staff/<int:role_pk>/edit', org.OrganizationRoleEdit.as_view(), name='org_staff_edit'),
    path('org/<int:org_pk>/staff/<int:role_pk>/remove', org.organization_role_delete_view, name='org_staff_remove'),
    path('org/<int:org_pk>/staff/request', org.OrganizationMembershipRequestCreate.as_view(), name='org_staff_request'),
    path('org/<int:org_pk>/staff/leave', org.OrganizationLeave.as_view(), name='org_staff_leave'),
    path('org/<int:org_pk>/staff/request/<int:request_pk>/', org.process_organization_membership_request_view, name='org_staff_request_review'),
    path('org/<int:org_pk>/staff/request/<int:request_pk>/review/<str:action>', org.process_organization_membership_request_view, name='org_staff_request_review_do'),
    path('org/<int:org_pk>/createproject', proj.ProjectCreateView.as_view(), name='proj_create'),
    path('org/createproject/select', proj.project_create_select_organization_view, name='proj_create_org_select'),

    path('proj/', proj.project_list_view, name='proj_list'),
    path('proj/<int:proj_pk>/', proj.ProjectView.as_view(), name='proj_info'),
    path('proj/<int:proj_pk>/edit', proj.ProjectEdit.as_view(), name='proj_info_edit'),
    path('proj/<int:proj_pk>/publish', proj.publish_project_view, name='proj_publish'),
    path('proj/<int:proj_pk>/finish', proj.finish_project_view, name='proj_finish'),
    path('proj/<int:proj_pk>/follow', proj.follow_project_view, name='proj_follow'),
    path('proj/<int:proj_pk>/log/', proj.ProjectLogView.as_view(), name='proj_log'),
    path('proj/<int:proj_pk>/discussion/', proj.project_comment_channel_index_view, name='proj_discussion'),
    path('proj/<int:proj_pk>/discussion/<int:channel_pk>/', proj.project_channel_comments_view, name='proj_discussion'),
    path('proj/<int:proj_pk>/discussion/<int:channel_pk>/add', proj.project_channel_comments_view, name='proj_discussion_add'),
    path('proj/<int:proj_pk>/scope/', proj.project_scope_view, name='proj_scope'),
    path('proj/<int:proj_pk>/scope/<int:scope_pk>/', proj.project_scope_view, name='proj_scope_previous'),
    path('proj/<int:proj_pk>/scope/<int:scope_pk>/edit', proj.project_edit_scope_view, name='proj_scope_edit'),
    path('proj/<int:proj_pk>/deliverables/', proj.ProjectDeliverablesView.as_view(), name='proj_deliverables'),
    path('proj/<int:proj_pk>/instructions/', proj.ProjectVolunteerInstructionsView.as_view(), name='proj_instructions'),
    path('proj/<int:proj_pk>/instructions/<int:task_pk>/', proj.ProjectVolunteerTaskDetailView.as_view(), name='proj_instructions_task'),
    path('proj/<int:proj_pk>/instructions/<int:task_pk>/review/<int:review_pk>/pin', proj.pin_task_review_view, name='proj_instructions_task_review_pin'),
    path('proj/<int:proj_pk>/task/', proj.ProjectTaskIndex.as_view(), name='proj_task_list'),
    path('proj/<int:proj_pk>/task/add', proj.create_default_project_task, name='proj_task_add'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/', proj.ProjectTaskDetailView.as_view(), name='proj_task'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/finish', proj.ProjectTaskReviewCreate.as_view(), name='proj_task_finish'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/publish', proj.publish_project_task_view, name='proj_task_publish'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/review/<int:review_pk>/', proj.process_task_review_request_view, name='proj_task_review'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/review/<int:review_pk>/resolve/<str:action>', proj.process_task_review_request_view, name='proj_task_review_do'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/cancel', proj.ProjectTaskCancel.as_view(), name='proj_task_cancel'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/apply', proj.ProjectTaskApply.as_view(), name='proj_task_apply'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/edit', proj.ProjectTaskEdit.as_view(), name='proj_task_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/togglevolunteers', proj.toggle_task_accepting_volunteers_view, name='proj_task_toggle_volunteers'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/delete', proj.ProjectTaskRemove.as_view(), name='proj_task_remove'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/<int:task_role_pk>', proj.ProjectTaskRoleRemove.as_view(), name='proj_volunteer_remove'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/<int:task_role_pk>/edit', proj.ProjectTaskRoleEdit.as_view(), name='proj_volunteer_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/application/<int:volunteer_application_pk>/', proj.volunteer_application_view, name='proj_volunteer_application_review'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/application/<int:volunteer_application_pk>/<str:action>', proj.volunteer_application_view, name='proj_volunteer_application_review_do'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/requirements', proj.project_task_requirements_edit_view, name='proj_task_requirements_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/staff', proj.project_task_staff_edit_view, name='proj_task_staff_edit'),
    path('proj/<int:proj_pk>/staff', proj.project_staff_view, name='proj_staff'),
    path('proj/<int:proj_pk>/staff/<int:role_pk>/edit', proj.ProjectRoleEdit.as_view(), name='proj_staff_edit'),
    path('proj/<int:proj_pk>/staff/<int:role_pk>/remove', proj.project_role_delete_view, name='proj_staff_remove'),
    path('proj/<int:proj_pk>/volunteers', proj.project_volunteers_view, name='proj_volunteers'),

    path('logout/', user.logout_view, name='logout'),
    path('login/', user.login_view, name='login'),

    path('signup/select', user.select_user_type_before, name='signup_type_select'),
    path('signup/do/<str:user_type>', user.signup, name='signup_form'),
    path('signup/do/<str:user_type>/via/<str:provider_id>/', user.signup_oauth, name='signup_oauth'),

    path('user/pwdchange', user.change_password, name='user_pwd_change'),
    path('user/pwdset', user.set_password, name='user_pwd_set'),
    path('user/connections/', user.social_connections, name='user_social_connections'),

    path('pwd/resetrequest', auth_views.PasswordResetView.as_view(template_name='marketplace/pwd_reset_request.html',
                                                                 success_url=reverse_lazy('marketplace:pwd_reset_request_done'),
                                                                 email_template_name='marketplace/password_reset_email.html',
                                                                 subject_template_name='marketplace/password_reset_email_subject.html'), name='pwd_reset_request'),
    path('pwd/resetrequest/done', auth_views.PasswordResetDoneView.as_view(template_name='marketplace/pwd_reset_request_done.html'), name='pwd_reset_request_done'),
    path('pwd/reset/<str:uidb64>/<str:token>', auth_views.PasswordResetConfirmView.as_view(template_name='marketplace/pwd_reset.html',
                                                                                            success_url=reverse_lazy('marketplace:pwd_reset_complete')), name='pwd_reset'),
    path('pwd/reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='marketplace/pwd_reset_complete.html'), name='pwd_reset_complete'),

    path('volunteers/', user.volunteer_list_view, name='volunteer_list'),
    path('user/', user.my_user_profile_view, name='my_user_profile'),
    path('user/dashboard/', user.UserHomeView.as_view(), name='user_dashboard'),
    path('user/select/', user.select_user_type_after, name='user_type_select'),
    path('user/<int:user_pk>', user.UserProfileView.as_view(), name='user_profile'),
    path('user/<int:user_pk>/edit', user.UserProfileEdit.as_view(), name='user_profile_edit'),
    path('user/<int:user_pk>/volunteercreate', user.create_volunteer_profile_view, name='user_volunteer_profile_create'),
    path('user/<int:user_pk>/<int:volunteer_pk>/edit', user.VolunteerProfileEdit.as_view(), name='user_volunteer_profile_edit'),
    path('user/<int:user_pk>/skills', user.user_profile_skills_edit_view, name='user_profile_skills_edit'),
    path('user/<int:user_pk>/preferences', user.user_preferences_edit_view, name='user_preferences_edit'),

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', include('marketplace.urls')),

    path('accounts/', include('marketplace.socialauth.account_urls')),
    path('accounts/', include('marketplace.socialauth.provider_urls')),

    path('admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

src/marketplace/models/common.py
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.db import models

class SocialCause():
    EDUCATION = 'ED'
    HEALTH = 'HE'
    ENVIRONMENT = 'EN'
    SOCIAL_SERVICES = 'SS'
    TRANSPORTATION = 'TR'
    ENERGY = 'EE'
    INTERNATIONAL_DEVELOPMENT = 'ID'
    PUBLIC_SAFETY = 'PS'
    ECONOMIC_DEVELOPMENT = 'EC'
    OTHER = 'OT'

    def get_choices():
        return (
                    (SocialCause.EDUCATION, 'Education'),
                    (SocialCause.HEALTH, 'Health'),
                    (SocialCause.ENVIRONMENT, 'Environment'),
                    (SocialCause.SOCIAL_SERVICES, 'Social Services'),
                    (SocialCause.TRANSPORTATION, 'Transportation'),
                    (SocialCause.ENERGY, 'Energy and Environment'),
                    (SocialCause.INTERNATIONAL_DEVELOPMENT, 'International development'),
                    (SocialCause.PUBLIC_SAFETY, 'Public Safety'),
                    (SocialCause.ECONOMIC_DEVELOPMENT, 'Economic Development'),
                    (SocialCause.OTHER, 'Other'),
                )

class ReviewStatus():
    NEW='NEW'
    ACCEPTED='ACC'
    REJECTED='REJ'

    def get_choices():
        return (
                (ReviewStatus.NEW, 'Pending review'),
                (ReviewStatus.ACCEPTED, 'Accepted'),
                (ReviewStatus.REJECTED, 'Rejected'),
                )

class Score():
    ONE_STAR = 1
    TWO_STARS = 2
    THREE_STARS = 3
    FOUR_STARS = 4
    FIVE_STARS = 5

    def get_choices():
        return (
                    (Score.ONE_STAR, 'Needs improvement'),
                    (Score.TWO_STARS, 'Fair'),
                    (Score.THREE_STARS, 'Good'),
                    (Score.FOUR_STARS, 'Excellent'),
                    (Score.FIVE_STARS, 'Outstanding'),
                )

class SkillLevel():
    BEGINNER = 0
    INTERMEDIATE = 1
    EXPERT = 2

    def get_choices():
        return (
                    (SkillLevel.BEGINNER, 'Beginner'),
                    (SkillLevel.INTERMEDIATE, 'Intermediate'),
                    (SkillLevel.EXPERT, 'Expert'),
                )

class OrgRole():
    ADMINISTRATOR = 0
    STAFF = 1

    def get_choices():
        return (
                    (OrgRole.ADMINISTRATOR, 'Administrator'),
                    (OrgRole.STAFF, 'Staff')
                )

# PHONE_REGEX = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")


def validate_image_size(value):
    filesize= value.size
    if filesize > 512000:
        raise ValidationError("The maximum image size that can be uploaded is 500KB.")
    else:
        return value

class TaskType():
    SCOPING_TASK='SCT'
    PROJECT_MANAGEMENT_TASK='PMT'
    DOMAIN_WORK_TASK='DWT'
    QA_TASK='QAT'

    def get_choices():
        return (
                    (TaskType.SCOPING_TASK, 'Project scoping'),
                    (TaskType.PROJECT_MANAGEMENT_TASK, 'Project management'),
                    (TaskType.DOMAIN_WORK_TASK, 'Data science'),
                    (TaskType.QA_TASK, 'QA'),
                )

src/marketplace/models/news.py
from django.db import models



class NewsPiece(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Title",
        blank=True,
        null=True,
    )
    contents = models.TextField(
        verbose_name="News contents",
        max_length=2000,
        blank=True,
        null=True,
    )
    link_url = models.URLField(
        verbose_name="External URL",
        max_length=200,
        blank=True,
        null=True,
    )
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modified_date = models.DateTimeField(auto_now= True)

src/marketplace/views/admin.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from rules.contrib.views import (
    PermissionRequiredMixin, objectgetter, permission_required,
)

from ..models.user import VolunteerProfile
from .common import build_breadcrumb, home_link, paginate

from marketplace.domain import marketplace
from marketplace.domain.user import UserService


def admin_link(include_link=True):
    return ('Admin', reverse_lazy('marketplace:admin_home') if include_link else None)


class AdminHomeView(PermissionRequiredMixin, generic.ListView):
    model = VolunteerProfile
    template_name = 'marketplace/admin_home.html'
    context_object_name = 'volunteer_profiles'
    paginate_by = 30
    permission_required = 'volunteer.new_user_review'
    raise_exception = True
    allow_empty = True

    def get_queryset(self):
        return marketplace.user.query_pending_volunteer_profiles(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumb'] = build_breadcrumb([home_link(), admin_link()])
        return context

    def get_permission_object(self):
        return self.request.user


def get_request_user(request, volunteer_pk, action):
    return request.user

@permission_required('volunteer.new_user_review', raise_exception=True, fn=get_request_user)
def review_volunteer_profile_view(request, volunteer_pk, action):
    if request.method == 'GET':
        raise Http404
    elif request.method == 'POST':
        try:
            if action == 'accept':
                UserService.accept_volunteer_profile(request.user, volunteer_pk)
            else:
                UserService.reject_volunteer_profile(request.user, volunteer_pk)
            return redirect('marketplace:admin_home')
        except KeyError as k:
            messages.error(request, str(k))
            return redirect('marketplace:admin_home')

src/marketplace/views/common.py
from itertools import repeat, zip_longest

from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator


def home_view(request):
    if request.user.is_authenticated:
        return render(request, 'marketplace/home_user.html')
    else:
        return render(request, 'marketplace/home_anonymous.html')

def about_view(request):
    return render(request, 'marketplace/about.html')

def resources_view(request):
    return render(request, 'marketplace/resources.html')

def home_link(include_link=True):
    return ('Home', reverse_lazy('marketplace:home') if include_link else None)

def build_breadcrumb(elements):
    # return [val for pair in zip_longest(elements, repeat((' > ', None), len(elements) - 1)) for val in pair if val is not None]
    return elements


def paginate(request, query_set, page_size=25, request_key='page'):
    paginator = Paginator(query_set, page_size)
    return paginator.get_page(request.GET.get(request_key, 1))


def generic_getter(domain_function, *args):
    try:
        result_object = domain_function(*args)
    except Exception as e:
        result_object = None
    if result_object:
        return result_object
    else:
        raise Http404

src/marketplace/templates/marketplace/components/filter_checkbox.html
<div class="form-check">
  <label class="form-check-label" for="{{ field_name }}{{ field_value }}">
    <input class="form-check-input"
           type="{{ field_type|default:'checkbox' }}"
           id="{{ field_name }}{{ field_value }}"
           name="{{ field_name }}"
           value="{{ field_value }}"
           {% if is_checked %}checked="checked"{% endif %}
           ></input>
    {{ field_text }}
  </label>
</div>

src/marketplace/templates/marketplace/components/inline_form_fields.html
{% load widget_tweaks %}

{% if form.errors %}
  <div class="alert alert-danger col-lg-12">
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

{% for field in form %}
  {% if field.errors %}
    <div class="form-group">
        <label class="control-label mr-1 text-danger" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="mr-5">
            {{ field|attr:"class:form-control is-invalid" }}
            <div class="invalid-feedback">
                {% for error in  field.errors %}{{ error }}{% endfor %}
            </div>
        </div>
    </div>
  {% else %}
    <label class="control-label mr-1" for="id_{{ field.name }}">{{ field.label }}</label>
    <div class="mr-5">
        {{ field|attr:"class:form-control" }}
    </div>
  {% endif %}
{% endfor %}

src/marketplace/templates/marketplace/components/navbar.html
{% load rules static %}

<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a id="dssglogo" class="navbar-brand" href="{% url 'marketplace:home' %}"><img src="{% static 'img/dssglogo.png' %}"></img></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item navbar-padder"></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:about' %}">About us</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:proj_list' %}">Projects</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:org_list' %}">Organizations</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:volunteer_list' %}">Volunteers</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:resources' %}">Resources</a></li>

      {% has_perm 'user.is_site_staff' user as is_site_staff %}
      {% if is_site_staff %}
        <li class="nav-item"><a class="nav-link text-warning" href="{% url 'marketplace:admin_home' %}">Admin</a></li>
      {% endif %}
      </ul>

      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:user_dashboard' %}">Dashboard</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:user_profile' user.id %}">My profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:logout' %}">Log out</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link btn btn-warning text-primary pl-4 pr-4 mr-3" href="{% url 'marketplace:signup_type_select' %}">Sign up</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'marketplace:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/marketplace/templates/marketplace/components/pagination.html
{% load params %}

{% if page_obj.has_other_pages %}
{% with pagename=pagename|default:'page' %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename 1 %}"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename page_obj.previous_page_number %}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link disabled" href="#"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
            <li class="page-item disabled"><a class="page-link disabled" href="#"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename page_obj.number|add:'-5' %}">&hellip;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
          {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename i %}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename page_obj.number|add:'5' %}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename page_obj.next_page_number %}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
            <li class="page-item"><a class="page-link" href="{% set_params_path pagename page_obj.paginator.num_pages %}"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link disabled" href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
            <li class="page-item disabled"><a class="page-link disabled" href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
        {% endif %}
  </ul>
</nav>
{% endwith %}
{% endif %}

src/marketplace/templates/marketplace/components/project_channels_index.html
{% if discussion_channels %}


<div class="card flex-column">
  <div class="card-header">Channels</div>
  <ul class="list-group list-group-flush">
  {% for chan in discussion_channels %}
      <a class="d-flex list-group-item list-group-item-action {% if chan.id == channel.id %}active{% endif %}"
         href="{% url 'marketplace:proj_discussion' project.id chan.id %}">
         <span class="mr-auto">
           {{ chan.name }}
         </span>
       </a>
  {% endfor %}
</ul>
</div>

{% endif %}

src/marketplace/templates/marketplace/components/signup_provider_list.html
{% load socialaccount %}

{% get_providers as socialaccount_providers %}

<form id="signup_oauth">
  <fieldset
      {% if form_disabled %}disabled="disabled"{% endif %}
  >

{% csrf_token %}

{% for preference in preferences %}
    <input type="hidden" name="preferences" value="{{ preference }}">
{% endfor %}

{% for provider in socialaccount_providers %}
      <button
          title="Sign up via {{provider.name}}"
          class="btn btn-outline-light provider {{provider.id}}"
          type="submit"
          form="signup_oauth"
          formaction="{% url 'marketplace:signup_oauth' user_type provider.id %}"
          formmethod="post"
      ><i class="fab fa-{{provider.id}}"></i>{{provider.name}}</button>
{% endfor %}

  </fieldset>
</form>

src/marketplace/templates/marketplace/components/type_select_signup.html
{% extends 'marketplace/components/type_select.html' %}

{% block type_select_organization %}
<a class="btn list-group-item list-group-item-action bg-success text-white" href="{% url 'marketplace:signup_form' 'organization' %}">
    Sign up as an organization member
</a>
{% endblock %}

{% block type_select_volunteer %}
<button
  type="submit"
  form="type_select"
  formaction="{% url 'marketplace:signup_form' 'volunteer' %}"
  formmethod="get"
  class="btn list-group-item list-group-item-action bg-success text-white">
 Sign up as a volunteer
</button>
{% endblock %}

src/marketplace/templates/marketplace/components/user_display.html
{% if not hide_anchor %}<a href="{% url 'marketplace:user_profile' user.id %}">{% endif %}

{% if user.full_name %}
  {{ user.full_name }}
  {% if include_username|default_if_none:True %}
    ({{ user.username }})
  {% endif %}
{% else %}
  {{ user.username }}
{% endif %}

{% for badge in user.userbadge_set.all %}
  {% include 'marketplace/components/user_badge.html' with badge=badge compact_display=True %}
{% endfor %}

{% if not hide_anchor %}</a>{% endif %}

src/marketplace/templates/marketplace/components/volunteer_tasks_index.html
{% if project_tasks %}


<div class="card flex-column">
  <div class="card-header">My Tasks</div>
  <ul class="list-group list-group-flush">
  {% for task in project_tasks %}
      <a class="d-flex list-group-item list-group-item-action {% if task == project_task %}active{% endif %}"
         href="{% url 'marketplace:proj_instructions_task' project.id task.id %}">
         <span class="mr-auto">
           {% include 'marketplace/components/task_type_display.html' with project_task=task compact_display=True %}
           {{ task.name }}
         </span>
         <span>
           {% include 'marketplace/components/task_stage_display.html' with project_task=task compact_display=True %}
         </span>
       </a>
  {% endfor %}
  </ul>
</div>
{% endif %}