src/marketplace/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView, TemplateView

from .views import common, org, proj, user, admin


# Set URL namespace
app_name = 'marketplace'

urlpatterns = [
    path('', user.home_view, name='home'),

    path('about/', common.about_view, name='about'),
    path('resources/', common.resources_view, name='resources'),

    path('terms/', RedirectView.as_view(pattern_name='marketplace:terms-20200804'), name='terms'),
    path('terms-20200804.html',
         TemplateView.as_view(template_name='marketplace/terms/terms-20200804.html',
                              extra_context={'privacy_url': 'marketplace:privacy-20200804'}),
         name='terms-20200804'),

    path('privacy/', RedirectView.as_view(pattern_name='marketplace:privacy-20200804'), name='privacy'),
    path('privacy-20200804.html',
         TemplateView.as_view(template_name='marketplace/privacy/privacy-20200804.html',
                              extra_context={'terms_url': 'marketplace:terms-20200804'}),
         name='privacy-20200804'),

    path('org/', org.organization_list_view, name='org_list'),
    path('org/create', org.OrganizationCreateView.as_view(), name='org_create'),
    path('org/create/<str:type>', org.OrganizationCreateView.as_view(), name='org_create_type'),
    path('org/<int:org_pk>/', org.OrganizationView.as_view(), name='org_info'),
    path('org/<int:org_pk>/edit', org.OrganizationEdit.as_view(), name='org_info_edit'),
    path('org/<int:org_pk>/staff/', org.organization_staff_view, name='org_staff'),
    path('org/<int:org_pk>/staff/add', org.add_organization_staff_view, name='org_staff_add'),
    path('org/<int:org_pk>/staff/<int:role_pk>/edit', org.OrganizationRoleEdit.as_view(), name='org_staff_edit'),
    path('org/<int:org_pk>/staff/<int:role_pk>/remove', org.organization_role_delete_view, name='org_staff_remove'),
    path('org/<int:org_pk>/staff/request', org.OrganizationMembershipRequestCreate.as_view(), name='org_staff_request'),
    path('org/<int:org_pk>/staff/leave', org.OrganizationLeave.as_view(), name='org_staff_leave'),
    path('org/<int:org_pk>/staff/request/<int:request_pk>/', org.process_organization_membership_request_view, name='org_staff_request_review'),
    path('org/<int:org_pk>/staff/request/<int:request_pk>/review/<str:action>', org.process_organization_membership_request_view, name='org_staff_request_review_do'),
    path('org/<int:org_pk>/createproject', proj.ProjectCreateView.as_view(), name='proj_create'),
    path('org/createproject/select', proj.project_create_select_organization_view, name='proj_create_org_select'),

    path('proj/', proj.project_list_view, name='proj_list'),
    path('proj/<int:proj_pk>/', proj.ProjectView.as_view(), name='proj_info'),
    path('proj/<int:proj_pk>/edit', proj.ProjectEdit.as_view(), name='proj_info_edit'),
    path('proj/<int:proj_pk>/publish', proj.publish_project_view, name='proj_publish'),
    path('proj/<int:proj_pk>/finish', proj.finish_project_view, name='proj_finish'),
    path('proj/<int:proj_pk>/follow', proj.follow_project_view, name='proj_follow'),
    path('proj/<int:proj_pk>/log/', proj.ProjectLogView.as_view(), name='proj_log'),
    path('proj/<int:proj_pk>/discussion/', proj.project_comment_channel_index_view, name='proj_discussion'),
    path('proj/<int:proj_pk>/discussion/<int:channel_pk>/', proj.project_channel_comments_view, name='proj_discussion'),
    path('proj/<int:proj_pk>/discussion/<int:channel_pk>/add', proj.project_channel_comments_view, name='proj_discussion_add'),
    path('proj/<int:proj_pk>/scope/', proj.project_scope_view, name='proj_scope'),
    path('proj/<int:proj_pk>/scope/<int:scope_pk>/', proj.project_scope_view, name='proj_scope_previous'),
    path('proj/<int:proj_pk>/scope/<int:scope_pk>/edit', proj.project_edit_scope_view, name='proj_scope_edit'),
    path('proj/<int:proj_pk>/deliverables/', proj.ProjectDeliverablesView.as_view(), name='proj_deliverables'),
    path('proj/<int:proj_pk>/instructions/', proj.ProjectVolunteerInstructionsView.as_view(), name='proj_instructions'),
    path('proj/<int:proj_pk>/instructions/<int:task_pk>/', proj.ProjectVolunteerTaskDetailView.as_view(), name='proj_instructions_task'),
    path('proj/<int:proj_pk>/instructions/<int:task_pk>/review/<int:review_pk>/pin', proj.pin_task_review_view, name='proj_instructions_task_review_pin'),
    path('proj/<int:proj_pk>/task/', proj.ProjectTaskIndex.as_view(), name='proj_task_list'),
    path('proj/<int:proj_pk>/task/add', proj.create_default_project_task, name='proj_task_add'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/', proj.ProjectTaskDetailView.as_view(), name='proj_task'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/finish', proj.ProjectTaskReviewCreate.as_view(), name='proj_task_finish'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/publish', proj.publish_project_task_view, name='proj_task_publish'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/review/<int:review_pk>/', proj.process_task_review_request_view, name='proj_task_review'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/review/<int:review_pk>/resolve/<str:action>', proj.process_task_review_request_view, name='proj_task_review_do'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/cancel', proj.ProjectTaskCancel.as_view(), name='proj_task_cancel'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/apply', proj.ProjectTaskApply.as_view(), name='proj_task_apply'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/edit', proj.ProjectTaskEdit.as_view(), name='proj_task_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/togglevolunteers', proj.toggle_task_accepting_volunteers_view, name='proj_task_toggle_volunteers'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/delete', proj.ProjectTaskRemove.as_view(), name='proj_task_remove'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/<int:task_role_pk>', proj.ProjectTaskRoleRemove.as_view(), name='proj_volunteer_remove'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/<int:task_role_pk>/edit', proj.ProjectTaskRoleEdit.as_view(), name='proj_volunteer_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/application/<int:volunteer_application_pk>/', proj.volunteer_application_view, name='proj_volunteer_application_review'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/volunteer/application/<int:volunteer_application_pk>/<str:action>', proj.volunteer_application_view, name='proj_volunteer_application_review_do'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/requirements', proj.project_task_requirements_edit_view, name='proj_task_requirements_edit'),
    path('proj/<int:proj_pk>/task/<int:task_pk>/staff', proj.project_task_staff_edit_view, name='proj_task_staff_edit'),
    path('proj/<int:proj_pk>/staff', proj.project_staff_view, name='proj_staff'),
    path('proj/<int:proj_pk>/staff/<int:role_pk>/edit', proj.ProjectRoleEdit.as_view(), name='proj_staff_edit'),
    path('proj/<int:proj_pk>/staff/<int:role_pk>/remove', proj.project_role_delete_view, name='proj_staff_remove'),
    path('proj/<int:proj_pk>/volunteers', proj.project_volunteers_view, name='proj_volunteers'),

    path('logout/', user.logout_view, name='logout'),
    path('login/', user.login_view, name='login'),

    path('signup/select', user.select_user_type_before, name='signup_type_select'),
    path('signup/do/<str:user_type>', user.signup, name='signup_form'),
    path('signup/do/<str:user_type>/via/<str:provider_id>/', user.signup_oauth, name='signup_oauth'),

    path('user/pwdchange', user.change_password, name='user_pwd_change'),
    path('user/pwdset', user.set_password, name='user_pwd_set'),
    path('user/connections/', user.social_connections, name='user_social_connections'),

    path('pwd/resetrequest', auth_views.PasswordResetView.as_view(template_name='marketplace/pwd_reset_request.html',
                                                                 success_url=reverse_lazy('marketplace:pwd_reset_request_done'),
                                                                 email_template_name='marketplace/password_reset_email.html',
                                                                 subject_template_name='marketplace/password_reset_email_subject.html'), name='pwd_reset_request'),
    path('pwd/resetrequest/done', auth_views.PasswordResetDoneView.as_view(template_name='marketplace/pwd_reset_request_done.html'), name='pwd_reset_request_done'),
    path('pwd/reset/<str:uidb64>/<str:token>', auth_views.PasswordResetConfirmView.as_view(template_name='marketplace/pwd_reset.html',
                                                                                            success_url=reverse_lazy('marketplace:pwd_reset_complete')), name='pwd_reset'),
    path('pwd/reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='marketplace/pwd_reset_complete.html'), name='pwd_reset_complete'),

    path('volunteers/', user.volunteer_list_view, name='volunteer_list'),
    path('user/', user.my_user_profile_view, name='my_user_profile'),
    path('user/dashboard/', user.UserHomeView.as_view(), name='user_dashboard'),
    path('user/select/', user.select_user_type_after, name='user_type_select'),
    path('user/<int:user_pk>', user.UserProfileView.as_view(), name='user_profile'),
    path('user/<int:user_pk>/edit', user.UserProfileEdit.as_view(), name='user_profile_edit'),
    path('user/<int:user_pk>/volunteercreate', user.create_volunteer_profile_view, name='user_volunteer_profile_create'),
    path('user/<int:user_pk>/<int:volunteer_pk>/edit', user.VolunteerProfileEdit.as_view(), name='user_volunteer_profile_edit'),
    path('user/<int:user_pk>/skills', user.user_profile_skills_edit_view, name='user_profile_skills_edit'),
    path('user/<int:user_pk>/preferences', user.user_preferences_edit_view, name='user_preferences_edit'),

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', include('marketplace.urls')),

    path('accounts/', include('marketplace.socialauth.account_urls')),
    path('accounts/', include('marketplace.socialauth.provider_urls')),

    path('admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

src/dssgmkt/models/orgmodels.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractUser
from dssgsolve import settings

from .commonmodels import (PHONE_REGEX, MAIN_CAUSE_CHOICES, EDUCATION,
                            ORGANIZATION_ROLE_CHOICES, ORGANIZATION_STAFF,
                            REVIEW_RESULT_CHOICES, NEW)


class Organization(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=5000)
    logo_url = models.URLField(max_length=200, blank=True, null=True)
    website_url = models.URLField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(validators=[PHONE_REGEX], max_length=17, blank=True, null=True)
    email_address = models.EmailField()
    street_address = models.CharField(max_length=300)
    address_line_2 = models.CharField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    country = CountryField()
    B100K = 'B000'
    B500K = 'B001'
    B1M = 'B005'
    B5M = 'B010'
    B20M = 'B050'
    B50M = 'B200'
    B50MP = 'B500'
    BUDGET_CHOICES = (
        (B100K, '<$100K'),
        (B500K, '$100K-$500K'),
        (B1M, '$500K-$1MM'),
        (B5M, '$1MM-$5MM'),
        (B20M, '$5MM-$20MM'),
        (B50M, '$20MM-$50MM'),
        (B50MP, '>$50MM')
    )
    budget = models.CharField(
        max_length=7,
        choices=BUDGET_CHOICES,
        default=B100K,
    )
    Y0 = 'Y00'
    Y1 = 'Y01'
    Y5 = 'Y05'
    Y10 = 'Y10'
    Y25 = 'Y25'
    OPERATION_YEARS_CHOICES = (
        (Y0, 'less than 1 year'),
        (Y1, '1 to 5 years'),
        (Y5, '5 to 10 years'),
        (Y10, '10 to 25 years'),
        (Y25, '25 or more years')
    )
    years_operation = models.CharField(
        max_length=3,
        choices=OPERATION_YEARS_CHOICES,
        default=Y0,
    )
    main_cause = models.CharField(
        max_length=2,
        choices=MAIN_CAUSE_CHOICES,
        default=EDUCATION,
    )
    LOCAL = 'LO'
    STATE = 'ST'
    REGION = 'RE'
    COUNTRY = 'CO'
    MULTINATIONAL = 'MN'
    OTHER = 'OT'
    ORGANIZATION_SCOPE_CHOICES = (
        (LOCAL, 'City/Local'),
        (STATE, 'State'),
        (REGION, 'Region (i.e. Midwest, Northeast, etc.)'),
        (COUNTRY, 'Country'),
        (MULTINATIONAL, 'Multi-national'),
        (OTHER, 'Other')
    )
    organization_scope = models.CharField(
        max_length=2,
        choices=ORGANIZATION_SCOPE_CHOICES,
        default=LOCAL,
    )
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modified_date = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.name

class OrganizationMembershipRequest(models.Model):
    role = models.IntegerField(choices = ORGANIZATION_ROLE_CHOICES, default=ORGANIZATION_STAFF)
    status = models.CharField(max_length=3, choices=REVIEW_RESULT_CHOICES, default=NEW)
    public_reviewer_comments = models.TextField(max_length=5000, blank=True, null=True)
    private_reviewer_notes = models.TextField(max_length=5000, blank=True, null=True)
    request_date = models.DateTimeField(auto_now_add=True)
    resolution_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def is_new(self):
        return self.status == NEW

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.status == ACCEPTED and not self.user.is_organization_member(self.organization):
            new_role = OrganizationRole(role = self.role, user = self.user, organization = self.organization)
            new_role.save()
## TODO move this to the logic in the views?

class OrganizationRole(models.Model):
    role = models.IntegerField(choices = ORGANIZATION_ROLE_CHOICES, default=ORGANIZATION_STAFF)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user','organization')

src/marketplace/models/news.py
from django.db import models



class NewsPiece(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Title",
        blank=True,
        null=True,
    )
    contents = models.TextField(
        verbose_name="News contents",
        max_length=2000,
        blank=True,
        null=True,
    )
    link_url = models.URLField(
        verbose_name="External URL",
        max_length=200,
        blank=True,
        null=True,
    )
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modified_date = models.DateTimeField(auto_now= True)

src/marketplace/views/admin.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from rules.contrib.views import (
    PermissionRequiredMixin, objectgetter, permission_required,
)

from ..models.user import VolunteerProfile
from .common import build_breadcrumb, home_link, paginate

from marketplace.domain import marketplace
from marketplace.domain.user import UserService


def admin_link(include_link=True):
    return ('Admin', reverse_lazy('marketplace:admin_home') if include_link else None)


class AdminHomeView(PermissionRequiredMixin, generic.ListView):
    model = VolunteerProfile
    template_name = 'marketplace/admin_home.html'
    context_object_name = 'volunteer_profiles'
    paginate_by = 30
    permission_required = 'volunteer.new_user_review'
    raise_exception = True
    allow_empty = True

    def get_queryset(self):
        return marketplace.user.query_pending_volunteer_profiles(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumb'] = build_breadcrumb([home_link(), admin_link()])
        return context

    def get_permission_object(self):
        return self.request.user


def get_request_user(request, volunteer_pk, action):
    return request.user

@permission_required('volunteer.new_user_review', raise_exception=True, fn=get_request_user)
def review_volunteer_profile_view(request, volunteer_pk, action):
    if request.method == 'GET':
        raise Http404
    elif request.method == 'POST':
        try:
            if action == 'accept':
                UserService.accept_volunteer_profile(request.user, volunteer_pk)
            else:
                UserService.reject_volunteer_profile(request.user, volunteer_pk)
            return redirect('marketplace:admin_home')
        except KeyError as k:
            messages.error(request, str(k))
            return redirect('marketplace:admin_home')

src/marketplace/templates/marketplace/org_staff.html
{% extends 'marketplace/org.html' %}

{% block tabcontents %}

  <h4 class="section-header">
    {% if organization.is_volunteer_group %}
      Members
    {% else %}
      Staff members
    {% endif %}
  </h4>
  {% if organization_staff %}
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
              <th>Full name</th>
              <th>Email address</th>
              <th>Role</th>
              <th>Member since</th>
              {% if user_is_administrator %}
              <th></th>
              <th></th>
              {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for staff in organization_staff %}
            <tr>
                <td>{% include 'marketplace/components/user_display.html' with user=staff.user %}</td>
                <td><a href="mailto:{{ staff.user.email }}">{{ staff.user.email }}</a></td>
                <td>{{ staff.get_role_display }}</td>
                <td>{{ staff.creation_date }}</td>
                {% if user_is_administrator %}
                <td>
                  <a href="{% url 'marketplace:org_staff_edit' staff.organization.id staff.id %}">
                    <i class="material-icons md-12" style="vertical-align: middle">edit</i>
                    Edit
                  </a>
                </td>
                <td>
                  <a class="text-danger" href="{% url 'marketplace:org_staff_remove' staff.organization.id staff.id %}">
                    <i class="material-icons" style="vertical-align: middle">remove_circle</i>
                    Remove
                  </a>
                </td>
                {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% url 'marketplace:org_staff' as org_staff_url %}
    {% include 'marketplace/components/pagination.html' with baseurl=org_staff_url page_obj=organization_staff pagename='staff_page' %}
  {% else %}
    <p>No staff found.</p>
  {% endif %}

  {% if user_is_administrator and organization.is_social_good_organization %}
    <h4 class="section-header">Add staff member</h4>
    <noscript>
      <style type="text/css">
        #addstaffajax {display:none;}
      </style>
      <form id="addstaff" class="form-inline">
        {% if form.errors %}
          <ol>
          {% for error in form.subject.errors %}
              <li><strong>{{ error|escape }}</strong></li>
          {% endfor %}
          </ol>
        {% endif %}

        {% csrf_token %}
        {% include 'marketplace/components/inline_form_fields.html' with form=add_staff_form %}

        <div class="form-group col-lg-3">
          <div>
            <button type="submit"
                    form="addstaff"
                    formaction="{% url 'marketplace:org_staff' organization.id %}"
                    formmethod="post"
                    class="btn btn-success">
              <i class="material-icons" style="vertical-align: middle">add_circle</i>
              Add staff member
            </button>
          </div>
        </div>
      </form>
    </noscript>

    <form id="addstaffajax" class="form-inline">
      {% if form_errors %}
        <div class="alert alert-danger col-lg-12">
          <ul>
            {% for error in form_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}


      <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
      <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
      <script src="/static/js/bootstrap3-typeahead.min.js"></script>

      {% csrf_token %}
       <div class="input-group">
        <label class="control-label mr-1" for="username">User</label>
        <div class="mr-5">
          <input type="text" data-provide="typeahead" class="form-control typeahead" name="username" id="username" placeholder="Type a user name..." autocomplete="off">
          <input type="hidden" id="userid" name="userid"></input>
        </div>
       </div>
        <div class="input-group">
         <label class="control-label mr-1" for="role">Role</label>
         <div class="mr-5">
           <select class="form-control" name="role" id="role">
             {% for role_value, role_name in organization_roles %}
                <option value="{{ role_value }}">{{ role_name }}</option>
             {% endfor %}
           </select>
          </div>
        </div>
       <script>
          var input = $('.typeahead');
          $('.typeahead').typeahead({
              source: function (query, process) {
                  return $.getJSON(
                      '/ajax/org/{{ organization.id }}/candidates/' + query,
                      {},
                      function (data) {
                          return process(data['users']);
                      })
              },
              afterSelect: function(x) {
                $('#userid').val(x['id'])
              }
          });

      </script>

      <div class="form-group col-lg-3">
        <div>
          <button type="submit"
                  form="addstaffajax"
                  formaction="{% url 'marketplace:org_staff_add' organization.id %}"
                  formmethod="post"
                  class="btn btn-success">
            <i class="material-icons" style="vertical-align: middle">add_circle</i>
            Add staff member
          </button>
        </div>
      </div>
    </form>



  {% endif %}

  <h4 class="section-header">Organization membership requests</h4>
  {% if organization_requests %}
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
              <th>Full name</th>
              <th>Email address</th>
              <th>Request date</th>
              <th>Status</th>
              <th>Resolution date</th>
          </tr>
        </thead>
        <tbody>
          {% for request in organization_requests %}
            <tr>
                <td>{% include 'marketplace/components/user_display.html' with user=request.user %}</td>
                <td><a href="mailto:{{ request.user.email }}">{{ request.user.email }}</a></td>
                <td>{{ request.request_date }}</td>
                <td>
                  <a href="{% url 'marketplace:org_staff_request_review' organization.id request.id %}"
                     class="{% if request.is_accepted %}
                               text-success
                             {% elif request.is_rejected %}
                               text-danger
                             {% elif request.is_new %}
                               text-info
                             {% endif %}">
                    <i class="material-icons" style="vertical-align: middle">
                      {% if request.is_accepted %}
                        check
                      {% elif request.is_rejected %}
                        block
                      {% elif request.is_new %}
                        edit
                      {% endif %}
                  </i>
                    {{ request.get_status_display }}
                  </a>
                </td>
                <td>{% if not request.is_new %}
                      {{ request.resolution_date|default_if_none:"" }}
                    {% endif %}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% url 'marketplace:org_staff' as org_staff_url %}
    {% include 'marketplace/components/pagination.html' with baseurl=org_staff_url page_obj=organization_requests pagename='requests_page' %}
  {% else %}
    <p>No requests found.</p>
  {% endif %}
{% endblock %}

src/marketplace/templates/marketplace/proj_create.html
{% extends 'marketplace/org.html' %}

{% block tabcontents %}


    <h4 class="section-header">Create new project</h4>


    <p>Create a new project of {{ organization.name }} that needs help from volunters.</p>

    <form id="createproject" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'marketplace/components/standard_form_fields.html' %}
      {% include 'marketplace/components/social_cause_edit_row.html' with label_text='Choose the social causes this project is focused on.' %}

      <div class="form-row">
        <div class="col-lg-9 offset-lg-3">
          <button type="submit"
                  form="createproject"
                  formaction="{% url 'marketplace:proj_create' organization.id %}"
                  formmethod="post"
                  class="btn btn-success mr-3">
            <i class="material-icons" style="vertical-align: middle">check</i>
            Create Project
          </button>
          <a class="btn btn-outline-primary" href="{% url 'marketplace:org_info' organization.id %}">
            <i class="material-icons" style="vertical-align: middle">close</i>
            Cancel
          </a>
        </div>
      </div>
    </form>


{% endblock %}

src/marketplace/templates/marketplace/proj_scope.html
{% extends "marketplace/proj.html" %}

{% block tabcontents %}

  {% load rules %}
  {% load markdown_deux_tags %}

  <div class="row section-header">
    <div class="col-lg-8">
      <h4>Project scope {% if not showing_current_scope %} (as of {{ current_scope.creation_date }}){% endif %}</h4>
    </div>

    <div class="col-lg-4">
      {% has_perm 'project.scope_edit' user project as perm_scope_edit %}
      {% if current_scope and showing_current_scope and perm_scope_edit and not project.is_completed_status and not project.is_expired_status %}
        <a class="btn btn-success col-lg-12 mb-1"
           href="{% url 'marketplace:proj_scope_edit' project.id current_scope.id %}">
          <i class="material-icons" style="vertical-align: middle">edit</i>
          Edit project scope
        </a>
      {% endif %}
    </div>
  </div>


  {% if current_scope.scope_goals %}
    <h5 class="section-header">Project goal(s)</h5>
    {{ current_scope.scope_goals|markdown }}
  {% endif %}

  {% if current_scope.scope_interventions %}
    <h5 class="section-header">Interventions and Actions</h5>
    {{ current_scope.scope_interventions|markdown }}
  {% endif %}

  {% if current_scope.scope_available_data %}
    <h5 class="section-header">Data</h5>
    {{ current_scope.scope_available_data|markdown }}
  {% endif %}

  {% if current_scope.scope_analysis %}
    <h5 class="section-header">Analysis Needed</h5>
    {{ current_scope.scope_analysis|markdown }}
  {% endif %}

  {% if current_scope.scope_validation_methodology %}
    <h5 class="section-header">Validation Methodology</h5>
    {{ current_scope.scope_validation_methodology|markdown }}
  {% endif %}
  
  {% if current_scope.scope_implementation %}
    <h5 class="section-header">Implementation</h5>
    {{ current_scope.scope_implementation|markdown }}
  {% endif %}

  <h4 class="section-header">Scope version notes</h4>
  <ul class="list-group list-group-flush mb-3">
    {% for scope in project_scopes %}
      <li class="list-group-item {% if current_scope and scope.creation_date > current_scope.creation_date %}bg-light{% endif %}">
        <div class="row">
          <div class="col-lg-3">
            <div class="text-right"><a href="{% url 'marketplace:user_profile' scope.author.id %}">{{ scope.author }}</a></div>
            <div class="text-right text-muted">{{ scope.creation_date }}</div>
          </div>
          <div class="col-lg-1">
            {% if scope != current_scope %}
              <a href="{% url 'marketplace:proj_scope_previous' project.id scope.id %}">View</a>
            {% else %}
              Showing
            {% endif %}
          </div>
          <div class="col-lg-8">
            {{ scope.version_notes|markdown }}
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>

  {% url 'marketplace:proj_scope' as proj_scope_url %}
  {% include 'marketplace/components/pagination.html' with baseurl=proj_scope_url page_obj=project_scopes %}

{% endblock %}